# Site settings
title: Junteng Liu
email: jliugi@connect.ust.hk
description: >-
  Personal academic homepage of Junteng Liu, first-year PhD candidate at HKUST NLP Group.
baseurl: ""
url: "https://rmanody.github.io/LJT-Homepage"
logo: /assets/images/headshot.jpg
github_username: Vicent0205
scholar_userid: tbK9jl4AAAAJ
twitter_username: junteng88716710

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
